//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyNumbers.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyNumbers.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Daniel Klecha.
        /// </summary>
        public static string AuthorAlertMessage {
            get {
                return ResourceManager.GetString("AuthorAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Author.
        /// </summary>
        public static string AuthorAlertTitle {
            get {
                return ResourceManager.GetString("AuthorAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AUTHOR.
        /// </summary>
        public static string AuthorButton {
            get {
                return ResourceManager.GetString("AuthorButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Correct answer, but the selected field is already taken!.
        /// </summary>
        public static string CellAlreadyTakenMessage {
            get {
                return ResourceManager.GetString("CellAlreadyTakenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Easy.
        /// </summary>
        public static string CpuDifficultyEasy {
            get {
                return ResourceManager.GetString("CpuDifficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hard.
        /// </summary>
        public static string CpuDifficultyHard {
            get {
                return ResourceManager.GetString("CpuDifficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Medium.
        /// </summary>
        public static string CpuDifficultyMedium {
            get {
                return ResourceManager.GetString("CpuDifficultyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CPU.
        /// </summary>
        public static string CpuText {
            get {
                return ResourceManager.GetString("CpuText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CPU is making a move....
        /// </summary>
        public static string CpuTurnTip {
            get {
                return ResourceManager.GetString("CpuTurnTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CRAZY.
        /// </summary>
        public static string CrazyLabel {
            get {
                return ResourceManager.GetString("CrazyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to leave the game? Your progress will be lost..
        /// </summary>
        public static string ExitAlertMessage {
            get {
                return ResourceManager.GetString("ExitAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exit Game.
        /// </summary>
        public static string ExitAlertTitle {
            get {
                return ResourceManager.GetString("ExitAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu A thrilling mathematical game of adjacency, calculation, and tactical grid occupation. Take turns to multiply and claim your territory!.
        /// </summary>
        public static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GAME OVER!.
        /// </summary>
        public static string GameOverTitle {
            get {
                return ResourceManager.GetString("GameOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GAME SETUP.
        /// </summary>
        public static string GameSetupTitle {
            get {
                return ResourceManager.GetString("GameSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Crazy Numbers.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GOT IT.
        /// </summary>
        public static string GotItButton {
            get {
                return ResourceManager.GetString("GotItButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu HOW TO PLAY.
        /// </summary>
        public static string HowToPlayButton {
            get {
                return ResourceManager.GetString("HowToPlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NEW GAME.
        /// </summary>
        public static string NewGameButton {
            get {
                return ResourceManager.GetString("NewGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NUMBERS.
        /// </summary>
        public static string NumbersLabel {
            get {
                return ResourceManager.GetString("NumbersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 1 Player.
        /// </summary>
        public static string OnePlayerText {
            get {
                return ResourceManager.GetString("OnePlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oops.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PLAYER {0}.
        /// </summary>
        public static string PlayerHeaderTemplate {
            get {
                return ResourceManager.GetString("PlayerHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PLAY GAME.
        /// </summary>
        public static string PlayGameButton {
            get {
                return ResourceManager.GetString("PlayGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu pts.
        /// </summary>
        public static string Pts {
            get {
                return ResourceManager.GetString("Pts", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to reset the game and return to the main screen?.
        /// </summary>
        public static string ResetAlertMessage {
            get {
                return ResourceManager.GetString("ResetAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reset Game.
        /// </summary>
        public static string ResetAlertTitle {
            get {
                return ResourceManager.GetString("ResetAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu RESET.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ROUND.
        /// </summary>
        public static string RoundLabel {
            get {
                return ResourceManager.GetString("RoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Each round consists of {0} player turns. The total turns in a game will be {0} times the number of rounds..
        /// </summary>
        public static string RoundsDescriptionTemplate {
            get {
                return ResourceManager.GetString("RoundsDescriptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu RULES.
        /// </summary>
        public static string RulesButton {
            get {
                return ResourceManager.GetString("RulesButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 1. The game displays the first factor (the player&apos;s active color).
        ///2. Select a second factor from the multiplier panel (numbers 1-9) at the bottom.
        ///3. Calculate the product (Factor 1 × Factor 2) and locate it on the board.
        ///4. Tap the cell with the correct product to claim it!
        ///5. Note: Tapping a wrong cell or a cell that is already taken passes your turn..
        /// </summary>
        public static string RulesHowToPlayDescription {
            get {
                return ResourceManager.GetString("RulesHowToPlayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu • How to Play.
        /// </summary>
        public static string RulesHowToPlayTitle {
            get {
                return ResourceManager.GetString("RulesHowToPlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Play solo against the CPU or with friends in 2 or 3-player mode. Players take turns making calculations to occupy cells on the 6x6 grid. The goal is to obtain the highest score by tactical positioning..
        /// </summary>
        public static string RulesPlayersDescription {
            get {
                return ResourceManager.GetString("RulesPlayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu • A 1, 2, or 3-Player Turn-Based Game.
        /// </summary>
        public static string RulesPlayersRule {
            get {
                return ResourceManager.GetString("RulesPlayersRule", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu - Diagonals: Occupying two fields diagonally scores 20 points.
        ///- Triplets: Occupying three consecutive fields horizontally or vertically scores a one-time 30-point bonus..
        /// </summary>
        public static string RulesScoringDescription {
            get {
                return ResourceManager.GetString("RulesScoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu • Scoring Rules.
        /// </summary>
        public static string RulesScoringTitle {
            get {
                return ResourceManager.GetString("RulesScoringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Crazy Numbers: Zigzag.
        /// </summary>
        public static string RulesSubtitle {
            get {
                return ResourceManager.GetString("RulesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu GAME RULES.
        /// </summary>
        public static string RulesTitle {
            get {
                return ResourceManager.GetString("RulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select CPU Difficulty.
        /// </summary>
        public static string SelectCpuDifficultyLabel {
            get {
                return ResourceManager.GetString("SelectCpuDifficultyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Number of Players.
        /// </summary>
        public static string SelectPlayersLabel {
            get {
                return ResourceManager.GetString("SelectPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Number of Rounds.
        /// </summary>
        public static string SelectRoundsLabel {
            get {
                return ResourceManager.GetString("SelectRoundsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu START GAME.
        /// </summary>
        public static string StartGameButton {
            get {
                return ResourceManager.GetString("StartGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 3 Players.
        /// </summary>
        public static string ThreePlayersText {
            get {
                return ResourceManager.GetString("ThreePlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select a multiplier from the bottom panel..
        /// </summary>
        public static string TipSelectMultiplier {
            get {
                return ResourceManager.GetString("TipSelectMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select the product on the grid..
        /// </summary>
        public static string TipSelectProduct {
            get {
                return ResourceManager.GetString("TipSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 2 Players.
        /// </summary>
        public static string TwoPlayersText {
            get {
                return ResourceManager.GetString("TwoPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WINNER.
        /// </summary>
        public static string WinnerLabel {
            get {
                return ResourceManager.GetString("WinnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WINNERS.
        /// </summary>
        public static string WinnersLabel {
            get {
                return ResourceManager.GetString("WinnersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unfortunately, that&apos;s the wrong answer!.
        /// </summary>
        public static string WrongAnswerMessage {
            get {
                return ResourceManager.GetString("WrongAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
